/**
 * This class is generated by jOOQ
 */
package com.ki.feature.entity;


import com.ki.feature.entity.tables.SchemaVersion;
import com.ki.feature.entity.tables.Teacher;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ki
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ki.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.ki.feature.entity.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>ki.TEACHER</code>.
     */
    public static final Teacher TEACHER = com.ki.feature.entity.tables.Teacher.TEACHER;
}
