/**
 * This class is generated by jOOQ
 */
package com.ki.common.codegen;


import com.ki.common.codegen.tables.Author;
import com.ki.common.codegen.tables.Book;
import com.ki.common.codegen.tables.BookStore;
import com.ki.common.codegen.tables.BookToBookStore;
import com.ki.common.codegen.tables.Student;
import com.ki.common.codegen.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ki extends SchemaImpl {

    private static final long serialVersionUID = -1438343811;

    /**
     * The reference instance of <code>ki</code>
     */
    public static final Ki KI = new Ki();

    /**
     * The table <code>ki.AUTHOR</code>.
     */
    public final Author AUTHOR = com.ki.common.codegen.tables.Author.AUTHOR;

    /**
     * The table <code>ki.BOOK</code>.
     */
    public final Book BOOK = com.ki.common.codegen.tables.Book.BOOK;

    /**
     * The table <code>ki.BOOK_STORE</code>.
     */
    public final BookStore BOOK_STORE = com.ki.common.codegen.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>ki.BOOK_TO_BOOK_STORE</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = com.ki.common.codegen.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>ki.STUDENT</code>.
     */
    public final Student STUDENT = com.ki.common.codegen.tables.Student.STUDENT;

    /**
     * The table <code>ki.USER</code>.
     */
    public final User USER = com.ki.common.codegen.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Ki() {
        super("ki", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Student.STUDENT,
            User.USER);
    }
}
