/**
 * This class is generated by jOOQ
 */
package com.ki.common.codegen;


import com.ki.common.codegen.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ki
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ki.USER</code>.
     */
    public static final User USER = com.ki.common.codegen.tables.User.USER;
}
